version: '3.8'

services:
  queue-service:
    build:
      context: ../../
      dockerfile: services/queue/Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_MAX_WORKERS=3
      - QUEUE_MAX_RETRIES=3
      - LOG_LEVEL=info
      - CONSUL_ADDR=consul:8500
    depends_on:
      - redis
      - consul
    networks:
      - mocks3-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8083/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - mocks3-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  consul:
    image: consul:1.17
    ports:
      - "8500:8500"
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - consul_data:/consul/data
    networks:
      - mocks3-network
    restart: unless-stopped
    command: >
      consul agent 
      -server 
      -bootstrap-expect=1 
      -data-dir=/consul/data 
      -config-dir=/consul/config 
      -ui-config-enabled=true 
      -client=0.0.0.0 
      -bind=0.0.0.0

volumes:
  redis_data:
    driver: local
  consul_data:
    driver: local

networks:
  mocks3-network:
    driver: bridge