# Grafana 数据源配置
# 自动配置 Prometheus 和 Elasticsearch 作为数据源

apiVersion: 1

datasources:
  # Prometheus 数据源 (指标)
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"
      queryTimeout: "60s"
      httpMethod: "POST"
    secureJsonData: {}

  # Elasticsearch 数据源 (日志)
  - name: Elasticsearch-Logs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "logs-mocks3*"
    isDefault: false
    editable: true
    jsonData:
      interval: "Daily"
      timeField: "@timestamp"
      esVersion: "8.0.0"
      logMessageField: "message"
      logLevelField: "level"
    secureJsonData: {}

  # Elasticsearch 数据源 (链路追踪)
  - name: Elasticsearch-Traces
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "traces-mocks3*"
    isDefault: false
    editable: true
    jsonData:
      interval: "Daily"
      timeField: "@timestamp"
      esVersion: "8.0.0"
    secureJsonData: {}

  # Jaeger 数据源 (备用链路追踪可视化)
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    isDefault: false
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: "elasticsearch-logs"
        tags: ["service", "span_id", "trace_id"]
        mappedTags: [
          { key: "service.name", value: "service" },
          { key: "span.id", value: "span_id" },
          { key: "trace.id", value: "trace_id" }
        ]
        mapTagNamesEnabled: true
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
    secureJsonData: {}