# Queue Service 配置
service:
  name: "queue-service"
  host: "queue-service"
  port: 8083

consul:
  address: "consul:8500"

# Redis配置
redis:
  url: "redis://redis:6379"
  password: ""
  db: 0

# Worker配置
worker:
  worker_count: 4
  poll_interval: "3s"

# 可观测性配置
observability:
  service_name: "queue-service"
  otlp_endpoint: "otel-collector:4318"
  log_level: "info"