# Prometheus 配置文件
# 用于从各种源收集指标数据

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'mocks3'
    environment: 'production'

# 规则文件配置
rule_files:
  - "alert_rules.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 抓取配置
scrape_configs:
  # Prometheus 自身监控
  - job_name: 'prometheus'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    scrape_interval: 15s
    static_configs:
      - targets: ['otel-collector:8888', 'otel-collector:8889']
    metrics_path: /metrics

  # MockS3 微服务 (通过 Consul 服务发现)
  - job_name: 'mocks3-services'
    scrape_interval: 15s
    consul_sd_configs:
      - server: 'consul:8500'
        services: 
          - metadata-service
          - storage-service
          - queue-service
          - third-party-service
          - mock-error-service
    relabel_configs:
      # 设置服务名标签
      - source_labels: [__meta_consul_service]
        target_label: service
      
      # 设置实例标签
      - source_labels: [__meta_consul_service_address, __meta_consul_service_port]
        separator: ':'
        target_label: instance
      
      # 设置地址
      - source_labels: [__meta_consul_service_address, __meta_consul_service_port]
        separator: ':'
        target_label: __address__
      
      # 添加环境标签
      - target_label: environment
        replacement: production
      
      # 添加命名空间标签
      - target_label: namespace
        replacement: mocks3

  # Nginx Gateway
  - job_name: 'nginx-gateway'
    scrape_interval: 30s
    static_configs:
      - targets: ['nginx-gateway:8080']
    metrics_path: /metrics
    scrape_timeout: 10s

  # 基础设施监控
  - job_name: 'infrastructure'
    scrape_interval: 30s
    static_configs:
      - targets: 
        - 'postgres:5432'
        - 'redis:6379'
        - 'consul:8500'
    metrics_path: /metrics

  # Node Exporter (如果部署)
  - job_name: 'node-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: []
        # - 'node-exporter:9100'

  # cAdvisor (容器监控)
  - job_name: 'cadvisor'
    scrape_interval: 30s
    static_configs:
      - targets: []
        # - 'cadvisor:8080'

# 存储配置 (retention.time 和 retention.size 通过命令行参数设置)

# 远程写入配置 (可选)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "user"
#       password: "password"