# Metadata Service 配置
service:
  name: "metadata-service"
  port: 8081
  host: "0.0.0.0"

consul:
  address: "consul:8500"

database:
  driver: "postgres"
  host: "postgres"
  port: 5432
  name: "mock_s3"
  username: "postgres"
  password: "postgres123"
  
redis:
  address: "redis:6379"
  password: ""
  db: 0

observability:
  service_name: "metadata-service"
  otlp_endpoint: "otel-collector:4318"
  log_level: "info"