# 全局配置
global:
  default_file_path: "./testdata"  # 默认文件保存路径

# Prometheus 区域与 URL 映射
prometheus:
  regions:
    mock: "http://127.0.0.1:9090/"
  port: 8090  # prometheus-mcp服务端口
  endpoint: "/prometheus"  # prometheus-mcp 服务路径

# Superset 相关配置
superset:
  base_url: "http://127.0.0.1:9090/"  # Superset 服务地址
  username: "username"                                    # 登录用户名
  password: "password"                                    # 登录密码
  port: 8091                                              # superset-mcp 服务端口
  endpoint: "/superset"                                   # superset-mcp 服务路径

#ElasticSearch相关配置
elasticsearch:
  port: 8092
  endpoint: "/es"
  # 索引配置
  index:
    pattern: "mock-{service}-logs-{date}"  # 索引模式，支持{service}和{date}占位符
    date_format: "2006.01.02"              # 日期格式，Go时间格式
    wildcard_pattern: "mock-*-logs-{date}" # 通配符模式，用于跨服务查询
  # 连接配置
  connection:
    base_url: "http://127.0.0.1:9200"      # Elasticsearch基础URL
    timeout: 30                            # 请求超时时间（秒）
    max_retries: 3                         # 最大重试次数
