apiVersion: v1
kind: ConfigMap
metadata:
  name: mock-s3-config
  namespace: zeroops
data:
  # Database configuration
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432" 
  POSTGRES_DB: "mocks3"
  POSTGRES_USER: "admin"
  
  # Redis configuration
  REDIS_ADDR: "redis:6379"
  REDIS_URL: "redis://redis:6379"
  
  # Consul configuration
  CONSUL_ADDR: "consul:8500"
  
  # OpenTelemetry configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  
---
apiVersion: v1
kind: Secret
metadata:
  name: mock-s3-secrets
  namespace: zeroops
type: Opaque
data:
  # Base64 encoded values
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password
  
---
# Storage Service 配置 - 共享存储方案
apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-service-config
  namespace: zeroops
data:
  storage-config.yaml: |
    # Storage Service 配置文件 - K8s多实例共享存储方案
    service:
      name: "storage-service"
      host: "0.0.0.0"
      port: 8082

    consul:
      address: "consul:8500"

    # 存储配置 - 共享存储节点，保持3倍冗余
    storage:
      root_path: "/app/data/storage"
      nodes:
        - id: "replica1"
          path: "/app/data/storage/replica1"
        - id: "replica2"
          path: "/app/data/storage/replica2"
        - id: "replica3"
          path: "/app/data/storage/replica3"

    # 外部服务配置
    services:
      metadata:
        url: "http://metadata-service:8081"
        timeout: "30s"
      queue:
        url: "http://queue-service:8083"
        timeout: "10s"
      third_party:
        url: "http://third-party-service:8084"
        timeout: "15s"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
  namespace: zeroops
data:
  consul-config.json: |
    {
      "datacenter": "dc1",
      "data_dir": "/consul/data",
      "log_level": "INFO",
      "server": true,
      "bootstrap": true,
      "ui_config": {
        "enabled": true
      },
      "connect": {
        "enabled": true
      },
      "acl": {
        "enabled": false
      }
    }